apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres_configmap.yaml
  - postgres_service.yaml
  - postgres_statefulset.yaml
  - postgres_volumeclaim.yaml
  - todo_backend_service.yaml
  - todo_backend_configmap.yaml
  - todo_backend_deployment.yaml
  - todo_app_service.yaml
  - todo_app_configmap.yaml
  - todo_app_deployment.yaml
  - cronjob_configmap.yaml
  - cronjob.yaml
  - shared_ingress.yaml
